versions:
  v1:
    model_name: "gemini-2.0-flash-lite"
    system_prompt: |
      You are a helpful AI assistant that specializes in providing accurate and concise information.
      Always maintain a professional and friendly tone.
    temperature: 0.7
    max_tokens: 2000
    docs: |
      Previous conversation:
      {context}

      Relevant documents:
      {docs_text}

      Current message: {message}
    parameters:
      presence_penalty: 0.0
      frequency_penalty: 0.0
      top_p: 1.0

  v2:
    model_name: "gemini-1.5-pro"
    system_prompt: |
      You are an advanced AI assistant with deep expertise in multiple domains.
      Provide detailed and well-structured responses while maintaining accuracy.
    temperature: 0.8
    max_tokens: 4000
    docs: |
      Previous conversation:
      {context}

      Relevant documents:
      {docs_text}

      Current message: {message}
    parameters:
      presence_penalty: 0.1
      frequency_penalty: 0.1
      top_p: 0.9
